# https://jupyterbook.org/customize/config.html

title: "Wuhao's Portfolio"
author: Wuhao

# https://jupyterbook.org/v1/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*
  - _build/*
  - "*.csv"

execute:
  execute_notebooks: "off"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
      - https://cdn.plot.ly/plotly-2.26.0.min.js   # <- 新增这行，加载 Plotly
    suppress_warnings: ["mystnb.unknown_mime_type"]

exclude:
  - .venv
  - _build
  - .github
  - .venv/
  - .github/