# _config.yml (最终修复版)

title: "Wuhao's Portfolio"
author: Wuhao Xia

only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*
  - _build/* # <-- 关键的新增行

execute:
  execute_notebooks: "off"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]